# Generated by Django 3.0.3 on 2021-03-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormal_image',
            name='image',
            field=models.ImageField(upload_to='media/abnormal_image'),
        ),
    ]
