
camera:
	python3 run_ngrok.py
run:
	python3 client.py
kill:
	pkill -f "rpi_camera_surveillance_system.py"
	pkill -f "ngrok"
	pkill -f "python3 client.py"
install:
	python3 install.py
arduino:
	python3 arduino.py
